Repository MicrosoftDocs/OfficeDocs-SharePoint, pull requests merged in 2018-12, with the labels that each got.

#474 Interoperability was spelled incorrectly
  SharePoint/SharePointServer/install/configure-client-certificate-authentication.md
Labels: Microsoft submitter

#436 Update pre-provision-accounts.md
  OneDrive/pre-provision-accounts.md
Labels: OneDrive

#489 SP2019 prereqs article touch ups
  SharePoint/SharePointServer/install/hardware-and-software-requirements-2019.md
Labels: Microsoft submitter

#466 Update to include reference to upload bandwidth policy
  OneDrive/redirect-known-folders.md
Labels: Microsoft submitter

#465 Update wording to include reference to KFM
  OneDrive/network-utilization-planning.md
Labels: Microsoft submitter

#499 Updated companies and content class rows in table
  SharePoint/SharePointServer/technical-reference/crawled-and-managed-properties-overview.md
Labels: Microsoft submitter

#519 Confusing statement about updating permissions
  OneDrive/upn-changes.md
Labels: Microsoft submitter

#493 Tweaks based on feedback from Red Room
  OneDrive/network-utilization-planning.md
  OneDrive/redirect-known-folders.md
  OneDrive/upn-changes.md
Labels: Microsoft submitter

#511 Update an-introduction-to-recommendations-and-popular-items.md
  SharePoint/SharePointServer/administration/an-introduction-to-recommendations-and-popular-items.md
Labels: SharePoint Server

#530 Removed an extra character >
  SharePoint/SharePointServer/governance/install-and-configure-workflow-for-sharepoint-server.md
Labels: Microsoft submitter
