Repository MicrosoftDocs/OfficeDocs-SharePoint, pull requests merged in 2022-06, with the labels that each got.

#3306 Fix Evaluation Center links
  SharePoint/SharePointServer/install/software-requirements-for-database-servers-for-sharepoint-server-subscription-edition.md
Labels: Microsoft submitter

#3301 Fix typo in article
  SharePoint/SharePointOnline/export-and-import-search-settings.md
Labels: Microsoft submitter

#3314 Update Disabling Integration Info
  SharePoint/SharePointOnline/sharepoint-azureb2b-integration.md
Labels: Microsoft submitter

#3315 Update default-timer-jobs-in-sharepoint-server-2019.md
  SharePoint/SharePointServer/technical-reference/default-timer-jobs-in-sharepoint-server-2019.md
Labels: Microsoft submitter

#3332 Update change-your-sharepoint-domain-name.md
  SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md
Labels: Microsoft submitter

#3344 Repo sync for protected CLA branch
  SharePoint/SharePointOnline/teams-connected-sites.md
Labels: Microsoft submitter, CLA

#3342 Repo sync for protected CLA branch
  migration/mm-setup-clients.md
Labels: Microsoft submitter, CLA

#3024 Update how to leverage proxy setting
  migration/how-to-format-your-csv-file-for-data-content-migration.md
Labels: Microsoft submitter

#3243 Update proxy connection setting
  migration/how-to-use-the-sharepoint-migration-tool.md
Labels: Microsoft submitter

#3345 Repo sync for protected CLA branch
  SharePoint/SharePointServer/install/new-onedrive-sync-client.md
  migration/mm-troubleshoot.md
Labels: Microsoft submitter, CLA

#3353 Repo sync for protected CLA branch
  OneDrive/One-Drive-Quickstart-Small-Business.md
  OneDrive/exclude-or-uninstall-previous-sync-client.md
  OneDrive/plan-onedrive-enterprise.md
  SharePoint/Hub/includes/sharepoint-content-updates.md
  SharePoint/SharePointOnline/corporate-communications-overview.md
  SharePoint/SharePointOnline/deprecation-of-site-mailboxes.md
  SharePoint/SharePointOnline/plan-communication-strategy.md
  migration/includes/migration-content-updates.md
Labels: CLA
