Repository MicrosoftDocs/OfficeDocs-SharePoint, pull requests merged in 2024-12, with the labels that each got.

#4214 Update limit-access.md
  SharePoint/SharePointOnline/limit-access.md
Labels: Microsoft submitter, one-drive/svc, Tier2

#4217 Update authentication-context-example.md
  SharePoint/SharePointOnline/authentication-context-example.md
Labels: sharepoint-online/svc, Tier2

#4212 Update block-file-types.md
  SharePoint/SharePointOnline/block-file-types.md
Labels: one-drive/svc
